dist: bionic
language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip3 install -r requirements.txt
  - curl https://raw.githubusercontent.com/algorand/algorand-sdk-testing/master/scripts/sdkupdate.sh -o ~/sdkupdate.sh
  - chmod +x ~/sdkupdate.sh

script:
  - python3 test_unit.py
  - ~/sdkupdate.sh --py