tasks:
# Docker tasks
- task: docker.Version
  arch: amd64
  configFilePath: cicd/docker/ci.Dockerfile
- task: shell.docker.Ensure
  name: builder
  arch: amd64
  image: algorand/py-algorand-sdk-ci-linux
  version: '{{ docker.Version.outputs.version }}'
  dockerFilePath: cicd/docker/ci.Dockerfile
  dependencies: docker.Version
- task: docker.Make
  name: unit
  docker:
    network: host
    image: algorand/py-algorand-sdk-ci-linux
    version: '{{ docker.Version.outputs.version }}'
  target: unit
- task: docker.Make
  name: integration
  docker:
    network: host
    image: algorand/py-algorand-sdk-ci-linux
    version: '{{ docker.Version.outputs.version }}'
  target: integration

# Harness tasks
- task: shell.Shell
  name: install-harness
  command: cicd/scripts/install-harness.sh
- task: shell.Shell
  name: start-harness
  command: cicd/scripts/start-harness.sh
- task: shell.Shell
  name: stop-harness
  command: cicd/scripts/stop-harness.sh


jobs:
  # Linux amd64 jobs
  test-linux-amd64-unit:
    tasks:
      - shell.docker.Ensure.builder
      - docker.Make.unit
  test-linux-amd64-integration:
    tasks:
      - shell.Shell.install-harness
      - shell.Shell.start-harness
      - shell.docker.Ensure.builder
      - docker.Make.integration
      - shell.Shell.stop-harness
