# Missing CODEC_ADDRESS in PYSDK examples (in ../docs/get-details/encoding.md:60)
# Missing CODEC_B64 in PYSDK examples (in ../docs/get-details/encoding.md:119)
# Missing CODEC_UINT64 in PYSDK examples (in ../docs/get-details/encoding.md:173)
# Missing CODEC_TRANSACTION_UNSIGNED in PYSDK examples (in ../docs/get-details/encoding.md:259)
# Missing CODEC_TRANSACTION_SIGNED in PYSDK examples (in ../docs/get-details/encoding.md:274)
# Missing CODEC_BLOCK in PYSDK examples (in ../docs/get-details/encoding.md:350)
# Missing CODEC_TRANSACTION_UNSIGNED in PYSDK examples (in ../docs/get-details/transactions/offline_transactions.md:44)
# Missing CODEC_TRANSACTION_SIGNED in PYSDK examples (in ../docs/get-details/transactions/offline_transactions.md:273)
